global inletpump_freq_actual
global inletpump_freq_nom 
global inletpump_freq_ref 
global inletpump_freq_man 
global inletpump_current 
global inletpump_power 
global inletpump_available 
global inletpump_starting 
global inletpump_running 
global inletpump_warning 
global inletpump_trip 
global inletpump_fault_reset 
global inletpump_remote 
global inletpump_manual 
global inletpump_start 
global inletpump_stop 
global inletpump_rpm 
global inletpump_sim_fault 
global inletpump_sim_remote 
global inletpump_sim_freq_ref 
global inletpump_sim_start 
global inletpump_sim_stop
global oxypump_freq_actual 
global oxypump_freq_nom 
global oxypump_freq_ref 
global oxypump_freq_man 
global oxypump_current 
global oxypump_power 
global oxypump_available 
global oxypump_starting 
global oxypump_running 
global oxypump_warning 
global oxypump_trip 
global oxypump_fault_reset 
global oxypump_remote 
global oxypump_manual 
global oxypump_start 
global oxypump_stop 
global oxypump_rpm 
global oxypump_sim_fault 
global oxypump_sim_remote 
global oxypump_sim_freq_ref 
global oxypump_sim_start 
global oxypump_sim_stop 