class OPCInitPen:
    def __init__(self,
        opc_object,
        address_space
        ):
        self.opc_object = opc_object
        self.address_space = address_space

    def init_opc(self):
        self.deltaH = self.opc_object.add_variable(self.address_space,"deltaH",0.0)
        self.deltaH_SP = self.opc_object.add_variable(self.address_space,"deltaH_SP",5.0)
        self.heighInsidePress1 = self.opc_object.add_variable(self.address_space,"heighInsidePress1",0.0)
        self.heighInsidePress2 = self.opc_object.add_variable(self.address_space,"heighInsidePress2",True)
        self.heighOutsidePress1 = self.opc_object.add_variable(self.address_space,"heighOutsidePress1",1.0)
        self.heighOutsidePress2 = self.opc_object.add_variable(self.address_space,"heighOutsidePress2",10.0)
        self.heighInsidePressSonic1 = self.opc_object.add_variable(self.address_space,"heighInsidePressSonic1",0.0)
        self.heighInsidePressSonic2 = self.opc_object.add_variable(self.address_space,"heighInsidePressSonic2",0.0)
        self.heighOutsidePressSonic1 = self.opc_object.add_variable(self.address_space,"heighOutsidePressSonic1",0.0)
        self.heighOutsidePressSonic2 = self.opc_object.add_variable(self.address_space,"heighOutsidePressSonic2",0.0)
        self.oxygen1 = self.opc_object.add_variable(self.address_space,"oxygen1",90.1)
        self.oxygen2 = self.opc_object.add_variable(self.address_space,"oxygen2",90.2)
        self.oxygen3 = self.opc_object.add_variable(self.address_space,"oxygen3",90.3)
        self.oxygen_outside1 = self.opc_object.add_variable(self.address_space,"oxygen_outside1",90.4)
        self.oxygen_outside2 = self.opc_object.add_variable(self.address_space,"oxygen_outside2",90.5)
        self.oxygen_consumption = self.opc_object.add_variable(self.address_space,"oxy_consumption",0.1)
        self.salinity1 = self.opc_object.add_variable(self.address_space,"salinity1",31.1)
        self.salinity2 = self.opc_object.add_variable(self.address_space,"salinity2",31.2)
        self.salinity3 = self.opc_object.add_variable(self.address_space,"salinity3",31.3)
        self.salinity_outside1 = self.opc_object.add_variable(self.address_space,"salinity_outside1",31.4)
        self.salinity_outside2 = self.opc_object.add_variable(self.address_space,"salinity_outside2",31.5)
        self.temperature1 = self.opc_object.add_variable(self.address_space,"temperature1",15.1)
        self.temperature2 = self.opc_object.add_variable(self.address_space,"temperature2",15.2)
        self.temperature3 = self.opc_object.add_variable(self.address_space,"temperature3",15.3)
        self.temperature_outside1 = self.opc_object.add_variable(self.address_space,"temperature_outside1",15.4)
        self.temperature_outside2 = self.opc_object.add_variable(self.address_space,"temperature_outside2",15.5)
        self.co2 = self.opc_object.add_variable(self.address_space,"co2",10.0)
        self.turbidity = self.opc_object.add_variable(self.address_space,"turbidity",0.6)
        self.tdgp = self.opc_object.add_variable(self.address_space,"tdgp",99.0)
        self.pH = self.opc_object.add_variable(self.address_space,"pH",8.0)
        self.level_outside1 = self.opc_object.add_variable(self.address_space,"level_outside1",70.1)
        self.level_outside2 = self.opc_object.add_variable(self.address_space,"level_outside2",70.2)
        self.level_outside3 = self.opc_object.add_variable(self.address_space,"level_outside3",70.3)
        self.level_inside1 = self.opc_object.add_variable(self.address_space,"level_inside1",77.1)
        self.level_inside2 = self.opc_object.add_variable(self.address_space,"level_inside2",77.2)
        self.level_inside3 = self.opc_object.add_variable(self.address_space,"level_inside3",77.3)
        self.draftsensor1 = self.opc_object.add_variable(self.address_space,"draftsensor1",74.0)
        self.draftsensor2 = self.opc_object.add_variable(self.address_space,"draftsensor2",72.0)
        self.draftsensor3 = self.opc_object.add_variable(self.address_space,"draftsensor3",70.0)
        self.oxyvalve = self.opc_object.add_variable(self.address_space,"oxyvalve",0.0)

        self.deltaH.set_writable()
        self.deltaH_SP.set_writable()
        self.heighInsidePress1.set_writable()
        self.heighInsidePress2.set_writable()
        self.heighOutsidePress1.set_writable()
        self.heighOutsidePress2.set_writable()
        self.heighInsidePressSonic1.set_writable()
        self.heighInsidePressSonic2.set_writable()
        self.heighOutsidePressSonic1.set_writable()
        self.heighOutsidePressSonic2.set_writable()
        self.oxygen1.set_writable()
        self.oxygen2.set_writable()
        self.oxygen3.set_writable()
        self.oxygen_outside1.set_writable()
        self.oxygen_outside2.set_writable()
        self.oxygen_consumption.set_writable()
        self.salinity1.set_writable()
        self.salinity2.set_writable()
        self.salinity3.set_writable()
        self.salinity_outside1.set_writable()
        self.salinity_outside2.set_writable()
        self.temperature1.set_writable()
        self.temperature2.set_writable()
        self.temperature3.set_writable()
        self.temperature_outside1.set_writable()
        self.temperature_outside2.set_writable()
        self.co2.set_writable()
        self.turbidity.set_writable()
        self.tdgp.set_writable()
        self.pH.set_writable()
        self.level_inside1.set_writable()
        self.level_inside2.set_writable()
        self.level_inside3.set_writable()
        self.level_outside1.set_writable()
        self.level_outside2.set_writable()
        self.level_outside3.set_writable()
        self.draftsensor1.set_writable()
        self.draftsensor2.set_writable()
        self.draftsensor3.set_writable()
        self.oxyvalve.set_writable()

    